### PR TITLE
added c.txt

### PR DESCRIPTION
**Pull request by williamzhu17**

### CODE REVIEW

**Review by atapas — CHANGES_REQUESTED** [review]
Add some content.

**Comment by williamzhu17** [comment]
wait i thought i did, but i recomitted and pushed

**Comment by atapas** [comment]
> wait i thought i did, but i recomitted and pushed

Have you added the text to c.txt? I do not see that change in the PR. Have you pushed?

**Comment by williamzhu17** [comment]
> > wait i thought i did, but i recomitted and pushed
> 
> Have you added the text to c.txt? I do not see that change in the PR. Have you pushed?

I believe I have added the text to c.txt. I am not sure why it is not showing up here. If you go to the c-file branch on github, it displays the text of the branch. When I pull and push on git, it says everything is up to date. I might just be misunderstanding something here. 

Capture

Capture(1)

**Comment by atapas** [comment]
We can do that live on Saturday. Hey, do you mind if we start 30 mins late
on this Saturday?


Regards,
- Tapas Adhikary
Twitter: @tapasadhikary <https://twitter.com/tapasadhikary>
Website: https://tapasadhikary.com

**Comment by williamzhu17** [comment]
Yeah for sure. We can start 30 mins later than normal. 
I also was able to finish the HTML pages, but I am probably going to wait to push them so that I don't mess everything up again.

**Comment by atapas** [comment]
Sounds good.

Regards,
Tapas Adhikary
https://tapasadhikary.com

**Review by atapas — APPROVED** [review]
LGTM

**Pull request merged**
